name: Deploy Content to tamarchecksagain [a3aaa57a-b63e-43cf-b9e1-cf11e3949419]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-a3aaa57a-b63e-43cf-b9e1-cf11e3949419.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main-sentinel-deployment ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-a3aaa57a-b63e-43cf-b9e1-cf11e3949419.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'bqiao-test-rg'
      workspaceName: 'tamarchecksagain'
      workspaceId: '3d4e7ed4-52df-4134-8066-3855fe2fac74'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AutomationRule'
      branch: 'main-sentinel-deployment'
      sourceControlId: 'a3aaa57a-b63e-43cf-b9e1-cf11e3949419'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_a3aaa57ab63e43cfb9e1cf11e3949419 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_a3aaa57ab63e43cfb9e1cf11e3949419 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_a3aaa57ab63e43cfb9e1cf11e3949419 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_a3aaa57ab63e43cfb9e1cf11e3949419 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_a3aaa57ab63e43cfb9e1cf11e3949419 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_a3aaa57ab63e43cfb9e1cf11e3949419 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_a3aaa57ab63e43cfb9e1cf11e3949419 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_a3aaa57ab63e43cfb9e1cf11e3949419 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_a3aaa57ab63e43cfb9e1cf11e3949419 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-a3aaa57a-b63e-43cf-b9e1-cf11e3949419.ps1